# 应用程序端口号
server:
  port: 8081


dubbo:
  application:
    # 定义了提供方应用信息，用于计算依赖关系；在 dubbo-admin 或 dubbo-monitor 会显示这个名字
    name: dubbo-service
  # 使用 zookeeper 注册中心暴露服务，注意要先开启 zookeeper
  registry:
    address: zookeeper://127.0.0.1:2181
  #  暴露端口
  protocol:
    port: 20880
# 服务版本号
  version: 1.0

