server:
  port: 8080

dubbo:
  application:
    name: blog-web
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.wener.blog.api
  version: 1.0